credentials:
  usernames:
    admin:
      email: admin@admin.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: admin
      password: password # Will be hashed automatically
cookie:
  expiry_days: 1
  key: auto_rsa_key # Must be string
  name: auto_rsa_login_cookie
pre-authorized:
  emails:
  # - melsby@gmail.com